In [52]:
import numpy as np
import matplotlib.pyplot as plt
import os
import open3d as o3d
import glob

ROOT = "data/rpi_custom_dataset_01/scene_1"

ModuleNotFoundError: No module named 'open3d'

# vizualization testing

In [30]:
data = np.loadtxt(os.path.join(ROOT, "scene_1.txt"), delimiter=",")

FileNotFoundError: data/rpi_custom_dataset_01/scene_1\scene_1.txt not found.

In [4]:
data.shape

(1702437, 6)

In [5]:
points = data[:, :3]
rgb = data[:, 3:6] / 255.0

In [6]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
pcd.colors = o3d.utility.Vector3dVector(rgb)

In [7]:
viz = o3d.visualization.Visualizer()
viz.create_window()
viz.add_geometry(pcd)
viz.run()
viz.destroy_window()

___

In [17]:
data = np.loadtxt(os.path.join(ROOT, "Coupling_4073350.txt"), delimiter=",")

In [18]:
points = data[:, :3]
rgb = data[:, 3:6] / 255.0

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
pcd.colors = o3d.utility.Vector3dVector(rgb)

viz = o3d.visualization.Visualizer()
viz.create_window()
viz.add_geometry(pcd)
viz.run()
viz.destroy_window()

getting the class names

In [2]:
anno_dir = os.path.join(ROOT, "Annotations")

In [5]:
len(os.listdir(anno_dir))

1218

In [6]:
n = os.listdir(anno_dir)[0]
n

'Conduit_1946940.txt'

In [7]:
n.split("_")[0]

'Conduit'

In [3]:
n = set(map(lambda x: x.rsplit("_", 1)[0], os.listdir(anno_dir)))

In [4]:
classes = list(n)
class2labels = {cls: i for i,cls in enumerate(classes)}

In [5]:
classes

['Elbow',
 'Stairs',
 'Mechanical_Equipment',
 'Conduit_Elbow',
 'Duct',
 'HSS_Channel',
 'Wall',
 'Electrical_Equipment',
 'Conduit',
 'Light',
 'Reducer',
 'Valve',
 'Pipe',
 'Transition',
 'Floor',
 'Receptacle',
 'Tee',
 'Pressure_Gauge',
 'Mullion',
 'Coupling',
 'C_Channel']

In [6]:
len(classes)

21

In [27]:
with open(r"data\rpi_custom_dataset_01_raw\classes.txt", "w") as f:
    for c in classes:
        f.write(f"{c}\n")

In [16]:
class2labels

{'Pressure_Gauge': 0,
 'Valve': 1,
 'Pipe': 2,
 'Stairs': 3,
 'Floor': 4,
 'C_Channel': 5,
 'Electrical_Equipment': 6,
 'Transition': 7,
 'Wall': 8,
 'Conduit': 9,
 'Conduit_Elbow': 10,
 'Mullion': 11,
 'Tee': 12,
 'Receptacle': 13,
 'Reducer': 14,
 'Coupling': 15,
 'Duct': 16,
 'Mechanical_Equipment': 17,
 'Elbow': 18,
 'HSS_Channel': 19,
 'Light': 20}

In [33]:
points_list = []

In [ ]:
for f in glob.glob(os.path.join(anno_dir, "*.txt")):
    cls = os.path.basename(f).rsplit("_", 1)[0]
    print(f)
    if cls not in classes:
        cls = 'clutter'

    points = np.loadtxt(f, delimiter=",")
    if points.ndim == 1:
        points = points.reshape(1, -1)
    labels = np.ones((points.shape[0],1)) * class2labels[cls]
    points_list.append(np.concatenate([points, labels], 1))



In [35]:
data_label = np.concatenate(points_list, 0)
xyz_min = np.amin(data_label, axis=0)[0:3]
data_label[:, 0:3] -= xyz_min

In [ ]:
data_label.shape

In [9]:
import colorsys

In [20]:
# data = np.load("data/rpi_custom_dataset_01/scene_1.npy")
data = np.load("data/stanford_indoor3d/Area_1_conferenceRoom_1.npy")

labels = data[:, 6].astype(int)

In [21]:
labels

array([3, 3, 3, ..., 2, 2, 2], shape=(1136617,))

In [26]:
CLASS_NAMES = ['Elbow',
 'Stairs',
 'Mechanical_Equipment',
 'Conduit_Elbow',
 'Duct',
 'HSS_Channel',
 'Wall',
 'Electrical_Equipment',
 'Conduit',
 'Light',
 'Reducer',
 'Valve',
 'Pipe',
 'Transition',
 'Floor',
 'Receptacle',
 'Tee',
 'Pressure_Gauge',
 'Mullion',
 'Coupling',
 'C_Channel']

In [23]:
CLASS_COLORS = []
n = len(CLASS_NAMES)
for i, name in enumerate(CLASS_NAMES):
    hue = i / n
    rgb = colorsys.hsv_to_rgb(hue, 0.9, 0.9)
    CLASS_COLORS.append([c for c in rgb])

In [24]:
CLASS_COLORS[labels]

TypeError: only integer scalar arrays can be converted to a scalar index

In [35]:
n = np.load("data\stanford_indoor3d\Area_1_conferenceRoom_1.npy")

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\jaspe\AppData\Local\Temp\ipykernel_24472\3328287651.py:1: SyntaxWarning: invalid escape sequence '\s'
  n = np.load("data\stanford_indoor3d\Area_1_conferenceRoom_1.npy")


In [36]:
n.shape

(1136617, 7)

In [37]:
n[0]

array([ 4.933,  2.703,  2.194, 71.   , 64.   , 54.   ,  3.   ])

In [38]:
n

array([[  4.933,   2.703,   2.194, ...,  64.   ,  54.   ,   3.   ],
       [  4.908,   2.716,   2.178, ...,  64.   ,  52.   ,   3.   ],
       [  4.92 ,   2.712,   2.175, ...,  61.   ,  52.   ,   3.   ],
       ...,
       [  5.203,   2.759,   0.335, ..., 103.   ,  87.   ,   2.   ],
       [  5.211,   2.741,   0.399, ..., 108.   ,  98.   ,   2.   ],
       [  5.191,   2.767,   0.279, ...,  99.   ,  92.   ,   2.   ]],
      shape=(1136617, 7))

# some model tests

In [7]:
import datetime
import importlib
import logging
import os
import shutil
import sys
import time
from pathlib import Path

import numpy as np
import torch
from tqdm import tqdm

import provider
from data_utils.S3DISDataLoader import S3DISDataset

from models import pointnet2_sem_seg

In [8]:
root = "data/stanford_indoor3d"
NUM_CLASSES = 13
NUM_POINT = 4096
BATCH_SIZE = 32

In [9]:
dataset = S3DISDataset(
    split="train",
    data_root=root,
    num_point=NUM_POINT,
    test_area=5,
    block_size=1.0,
    sample_rate=1.0,
    transform=None
)

100%|██████████| 204/204 [00:30<00:00,  6.59it/s]

[1.124833  1.1816078 1.        2.2412012 2.340336  2.343587  1.7070498
 2.0335796 1.8852289 3.8252103 1.7948895 2.7857335 1.3452303]
Totally 47623 samples in train set.


In [12]:
dataset[0][0].shape

(4096, 9)

In [7]:
classifier = pointnet2_sem_seg.get_model(NUM_CLASSES).cuda()
classifier = classifier.eval()

In [8]:
len(dataset)

47623

In [9]:
points, labels = dataset[0]

In [10]:
points = torch.Tensor(points).float().cuda()
labels = torch.Tensor(labels).long().cuda()

In [11]:
# add batch dim
points = points.unsqueeze(0)
labels = labels.unsqueeze(0)

In [12]:
points = points.transpose(2, 1)

In [13]:
seg_pred, _ = classifier(points)

In [14]:
seg_pred = seg_pred.contiguous().view(-1, NUM_CLASSES)

In [15]:
seg_pred.shape

torch.Size([4096, 13])

In [16]:
pred_val = seg_pred.contiguous().cpu().data.numpy()
pred_val = np.argmax(pred_val, 1)

In [17]:
pred_val

array([10, 10, 10, ..., 10, 10, 10])

In [18]:
labels.shape

torch.Size([1, 4096])

In [19]:
labels

tensor([[12,  0, 12,  ...,  2,  2,  2]], device='cuda:0')

In [20]:
points, _ = dataset[0]
points.shape

(4096, 9)

In [21]:
p = np.column_stack(( points, pred_val ))
p.shape

(4096, 10)

In [22]:
p

array([[-2.00000000e-02, -2.02000000e-01,  1.61500000e+00, ...,
         3.09658393e-01,  5.68061906e-01,  1.00000000e+01],
       [ 4.36000000e-01, -3.45000000e-01,  1.86500000e+00, ...,
         2.74514623e-01,  6.55997186e-01,  1.00000000e+01],
       [-4.90000000e-02,  2.50000000e-02,  2.53400000e+00, ...,
         3.65446056e-01,  8.91311994e-01,  1.00000000e+01],
       ...,
       [ 4.40000000e-02, -3.35000000e-01,  1.38900000e+00, ...,
         2.76972229e-01,  4.88568414e-01,  1.00000000e+01],
       [ 3.47000000e-01,  3.47000000e-01,  3.00000000e-03, ...,
         4.44580978e-01,  1.05522336e-03,  1.00000000e+01],
       [ 2.66000000e-01, -2.61000000e-01,  1.40000000e-02, ...,
         2.95158516e-01,  4.92437566e-03,  1.00000000e+01]])

In [23]:
######################

In [39]:
points, target = dataset[0]
points, target = torch.Tensor(points).float().cuda().unsqueeze(0), torch.Tensor(target).float().cuda().unsqueeze(0)
points = points.transpose(2, 1)
points.shape, target.shape

(torch.Size([1, 9, 4096]), torch.Size([1, 4096]))

In [40]:
points = points.squeeze(0).cpu().numpy().transpose(1, 0)
target = target.squeeze(0).cpu().numpy()
points.shape, target.shape

((4096, 9), (4096,))

In [41]:
points = points[:, 0:6]
points.shape

(4096, 6)

In [42]:
import open3d as o3d

In [45]:
def make_pcd(data, color_mode="rgb"):
    pc = data[:, :3]
    rgb = data[:, 3:6]
    # labels = data[:, 6].astype(int)

    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(pc)
    # pcd.colors = o3d.utility.Vector3dVector(
    #     CLASS_COLORS[labels] if color_mode == "label" else rgb
    # )
    pcd.colors = o3d.utility.Vector3dVector(rgb)
    return pcd, points

pcd, _ = make_pcd(points)

In [46]:
viz = o3d.visualization.Visualizer()
viz.create_window()
viz.add_geometry(pcd)
viz.run()
viz.destroy_window()

# dataset testing

In [1]:
from data_utils.RPIDataLoader import PointNetDataset

In [2]:
data_root = "data/rpi_data"
num_point, block_size, sample_rate, num_classes = 4096, 1.0, 0.01, 21

point_data = PointNetDataset(
    split="train",
    data_root=data_root,
    num_point=num_point,
    num_classes=num_classes,
    block_size=block_size,
    sample_rate=sample_rate,
    transform=None,
)

Loading data from data/rpi_data for train set
Params: num_point=4096, block_size=1.0, sample_rate=0.01


  0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 1/1 [00:00<00:00,  5.01it/s]

[ 1.2249647  3.8467453  1.5205659  3.2069242  2.6301715  1.
  5.564438   2.2240953  7.6580505  1.5681067  3.8029714  3.9385123
  1.828945   1.5156392  5.1053066 10.691696   1.4688611  9.017725
 12.683751   2.5211787  4.831601 ]
Totally 3 samples in train set.


In [6]:
import torch
from torch.utils.data import DataLoader
import numpy as np

In [15]:
trainDataLoader = torch.utils.data.DataLoader(
        point_data,
        batch_size=32,
        shuffle=True,
        num_workers=1,
        pin_memory=True,
        # drop_last=True,
        persistent_workers=True,
        worker_init_fn=lambda x: np.random.seed(x + int(time.time())),
    )

len(trainDataLoader)

1

In [14]:
len(trainDataLoader)

0

In [52]:
print("point data size:", point_data.__len__())
print("point data 0 shape:", point_data.__getitem__(0)[0].shape)
print("point label 0 shape:", point_data.__getitem__(0)[1].shape)

point data size: 8
point data 0 shape: (4096, 9)
point label 0 shape: (4096,)


In [13]:
point_data[0][1].shape

(4096,)

In [33]:
class DatasetWholeScene:
    # prepare to give prediction on each points
    def __init__(
        self,
        root,
        block_points=4096,
        stride=0.5,
        block_size=1.0,
        padding=0.001,
        num_classes=21,
    ):
        self.block_points = block_points
        self.block_size = block_size
        self.padding = padding
        self.root = root
        self.stride = stride
        self.scene_points_num = []
        self.file_list = [
            d for d in os.listdir(root)
        ]
        self.scene_points_list = []
        self.semantic_labels_list = []
        self.room_coord_min, self.room_coord_max = [], []
        for file in self.file_list:
            data = np.load(os.path.join(root, file))
            points = data[:, :3]
            self.scene_points_list.append(data[:, :6])
            self.semantic_labels_list.append(data[:, 6])
            coord_min, coord_max = (
                np.amin(points, axis=0)[:3],
                np.amax(points, axis=0)[:3],
            )
            # self.room_coord_min.append(coord_min), self.room_coord_max.append(coord_max)
        assert len(self.scene_points_list) == len(self.semantic_labels_list)

        labelweights = np.zeros(num_classes)
        for seg in self.semantic_labels_list:
            tmp, _ = np.histogram(seg, range(num_classes + 1))
            self.scene_points_num.append(seg.shape[0])
            labelweights += tmp
        labelweights = labelweights.astype(np.float32)
        labelweights = labelweights / np.sum(labelweights)
        self.labelweights = np.power(np.amax(labelweights) / labelweights, 1 / 3.0)

    def __getitem__(self, index):
        point_set_ini = self.scene_points_list[index]
        points = point_set_ini[:, :6]
        labels = self.semantic_labels_list[index]
        coord_min, coord_max = np.amin(points, axis=0)[:3], np.amax(points, axis=0)[:3]
        grid_x = int(
            np.ceil(float(coord_max[0] - coord_min[0] - self.block_size) / self.stride)
            + 1
        )
        grid_y = int(
            np.ceil(float(coord_max[1] - coord_min[1] - self.block_size) / self.stride)
            + 1
        )
        data_room, label_room, sample_weight, index_room = (
            np.array([]),
            np.array([]),
            np.array([]),
            np.array([]),
        )
        for index_y in range(0, grid_y):
            for index_x in range(0, grid_x):
                s_x = coord_min[0] + index_x * self.stride
                e_x = min(s_x + self.block_size, coord_max[0])
                s_x = e_x - self.block_size
                s_y = coord_min[1] + index_y * self.stride
                e_y = min(s_y + self.block_size, coord_max[1])
                s_y = e_y - self.block_size
                point_idxs = np.where(
                    (points[:, 0] >= s_x - self.padding)
                    & (points[:, 0] <= e_x + self.padding)
                    & (points[:, 1] >= s_y - self.padding)
                    & (points[:, 1] <= e_y + self.padding)
                )[0]
                if point_idxs.size == 0:
                    continue
                num_batch = int(np.ceil(point_idxs.size / self.block_points))
                point_size = int(num_batch * self.block_points)
                replace = (
                    False if (point_size - point_idxs.size <= point_idxs.size) else True
                )
                point_idxs_repeat = np.random.choice(
                    point_idxs, point_size - point_idxs.size, replace=replace
                )
                point_idxs = np.concatenate((point_idxs, point_idxs_repeat))
                np.random.shuffle(point_idxs)
                data_batch = points[point_idxs, :]
                normlized_xyz = np.zeros((point_size, 3))
                normlized_xyz[:, 0] = data_batch[:, 0] / coord_max[0]
                normlized_xyz[:, 1] = data_batch[:, 1] / coord_max[1]
                normlized_xyz[:, 2] = data_batch[:, 2] / coord_max[2]
                data_batch[:, 0] = data_batch[:, 0] - (s_x + self.block_size / 2.0)
                data_batch[:, 1] = data_batch[:, 1] - (s_y + self.block_size / 2.0)
                data_batch[:, 3:6] /= 255.0
                data_batch = np.concatenate((data_batch, normlized_xyz), axis=1)
                label_batch = labels[point_idxs].astype(int)
                batch_weight = self.labelweights[label_batch]

                data_room = (
                    np.vstack([data_room, data_batch]) if data_room.size else data_batch
                )
                label_room = (
                    np.hstack([label_room, label_batch])
                    if label_room.size
                    else label_batch
                )
                sample_weight = (
                    np.hstack([sample_weight, batch_weight])
                    if label_room.size
                    else batch_weight
                )
                index_room = (
                    np.hstack([index_room, point_idxs])
                    if index_room.size
                    else point_idxs
                )
        data_room = data_room.reshape((-1, self.block_points, data_room.shape[1]))
        label_room = label_room.reshape((-1, self.block_points))
        sample_weight = sample_weight.reshape((-1, self.block_points))
        index_room = index_room.reshape((-1, self.block_points))
        return data_room, label_room, sample_weight, index_room

    def __len__(self):
        return len(self.scene_points_list)



In [34]:
data = DatasetWholeScene(root="data/rpi_data", block_points=4096, stride=0.5, block_size=1.0, padding=0.001, num_classes=21)

In [35]:
data_room, label_room, sample_weight, index_room = data[0]

In [37]:
data.file_list

['scene_1.npy']

In [36]:
data_room.shape, label_room.shape, sample_weight.shape, index_room.shape

((1932, 4096, 9), (1932, 4096), (1932, 4096), (1932, 4096))

In [40]:
whole_data_scene = data.scene_points_list[0]
whole_data_scene.shape

(1488600, 6)

In [41]:
whole_data_label = data.semantic_labels_list[0]
whole_data_label.shape

(1488600,)

In [42]:
BATCH_SIZE = 32

In [43]:
num_blocks = data_room.shape[0]
s_batch_num = (num_blocks + BATCH_SIZE - 1) // BATCH_SIZE

In [44]:
sbatch = 0
start_idx = sbatch * BATCH_SIZE
end_idx = min((sbatch + 1) * BATCH_SIZE, num_blocks)
real_batch_size = end_idx - start_idx

In [45]:
batch_data = data_room[start_idx:end_idx]
batch_label = label_room[start_idx:end_idx]
batch_data.shape, batch_label.shape

((32, 4096, 9), (32, 4096))

In [46]:
from models import pointnet2_sem_seg

In [47]:
NUM_CLASSES = 21
classifier = pointnet2_sem_seg.get_model(NUM_CLASSES).cuda()

In [49]:
torch_data = torch.Tensor(batch_data)
torch_data = torch_data.float().cuda()
torch_data = torch_data.transpose(2, 1)
seg_pred, _ = classifier(torch_data)
batch_pred_label = seg_pred.contiguous().cpu().data.max(2)[1].numpy()

# inference pipeline test

In [17]:
import argparse
import os
from data_utils.RPIDataLoader import DatasetWholeScene
from data_utils.indoor3d_util import g_label2color
import torch
import logging
from pathlib import Path
import sys
import importlib
from tqdm import tqdm
import provider
import numpy as np
from models import pointnet2_sem_seg



In [19]:
NUM_CLASSES = 21

In [20]:
model = pointnet2_sem_seg.get_model(NUM_CLASSES).cuda()

In [23]:
data = np.load("data/rpi_data/train_scene_1.npy")

In [24]:
data.shape

(1488600, 7)

In [25]:
points = data[:, :6]
labels = data[:, 6].astype(int)
points.shape, labels.shape

((1488600, 6), (1488600,))

In [26]:
from RPIDataLoader import DatasetWholeScene

In [27]:
ds = DatasetWholeScene(root="data/rpi_data", block_points=4096, stride=0.5, block_size=1.0, padding=0.001, num_classes=21)

In [28]:
points = ds[0]

(1932, 4096, 9)

1488600

# more testing 

In [1]:
import os
import numpy as np
import glob
import colorsys

In [12]:
ROOT = "rpi_data_raw"

In [10]:
classes = []
scenes = os.listdir(ROOT)
for scene in scenes:
    anno_dir = os.path.join(ROOT,scene, "_PointOut")
    anno = os.listdir(anno_dir)
    # print(f"Scene: {scene}, Number of Annotations: {len(anno)}")
    for a in anno:
        if ".xyz" in a:
            cls = a.rsplit("_", 1)[0]
            if cls not in classes:
                classes.append(cls)
classes
    

['Bathroom_Equipment',
 'Casework',
 'Ceiling',
 'Column',
 'Conduit',
 'Conduit_Elbow',
 'Coupling',
 'CurtainWall',
 'Door',
 'Duct',
 'Elbow',
 'Electrical_Equipment',
 'Electric_Receptacle',
 'Fire_Alarm',
 'Fire_Equipment',
 'Fixture',
 'Floor',
 'GenericModel',
 'Handle',
 'Light',
 'Mechanical_Equipment',
 'Pipe',
 'Plumbing',
 'Railing',
 'Roof',
 'Sign',
 'Sink',
 'Sprinkler',
 'Stair',
 'Tee',
 'Truss',
 'Wall',
 'Window']

In [19]:
if not os.path.exists(ROOT):
    print("dne  ")

dne  


In [ ]:
jos.mkdir()

In [17]:
l = ["hi", "my", "name", "is", "jasper"]
with open("test.txt", "w") as file:
    for n in l:
        file.write(n + "\n")

In [18]:
os.listdir("zips")

['101 S Franklin St - R24 Bank.zip',
 '1342 Central Ave - R24 Firestation.zip',
 '2187 Victory Blvd - Apartment Complex.zip',
 '280 Park Ave - Large Office.zip',
 '290 Congress Ave.zip',
 '333 W 34th - Department Store.zip',
 '339 W 47th St - Brownstone with Roof MEP.zip',
 '50 UN Plaza - Residential Condo.zip',
 '537 Decatur St - Brownstone with Basement MEP.zip',
 '618 Main St - Bank.zip',
 '622 Cabrillo Ave.zip',
 '9 Trefoil Dr - R24 Large Office Building.zip',
 'Vorheer.zip']

In [1]:
os.path.isdir("zips.txt")

NameError: name 'os' is not defined

# more debugging

In [1]:
import numpy as np
from pathlib import Path
import os
from torch.utils.data import DataLoader
from tqdm import tqdm
import torch
import time

In [2]:
torch.cuda.device_count()

8

In [3]:
device = "cuda:0"

In [4]:
data_root = "rpi_data"

In [5]:
from models.pointnet2_sem_seg import get_model
from data_utils.RPIDataLoader import PointNetDataset

In [6]:
model = get_model(47).cuda()

In [6]:
ds = PointNetDataset(
        split="test",
        data_root=data_root,
        num_point=2048,
        num_classes=47,
        block_size=1.0,
        sample_rate=1.0,
        transform=None,
    )

Loading data from rpi_data for test set
Params: num_point=2048, block_size=1.0, sample_rate=1.0


100%|██████████| 4/4 [00:30<00:00,  7.53s/it]
/home/nvidia/Pointnet_Pointnet2_pytorch/data_utils/RPIDataLoader.py:70: RuntimeWarning: divide by zero encountered in divide
  np.power(np.amax(labelweights) / labelweights, 1 / 3.0)
100%|██████████| 4/4 [00:28<00:00,  7.16s/it]

Totally 116555 samples in test set.


In [15]:
dataloader = DataLoader(
    ds,
    batch_size =128,
    shuffle = True,
    num_workers = 0,
    # persistent_workers = True,
    pin_memory = True,
    # worker_init_fn=lambda id: np.random.seed(id)
)

In [16]:
import time

# Test raw __getitem__ calls (no DataLoader overhead)
start = time.time()
items = [ds[i] for i in range(64)]
print(f"64 raw __getitem__ calls: {time.time()-start:.3f}s")

# Test just creating the iterator
start = time.time()
it = iter(dataloader)
print(f"iter(dataloader): {time.time()-start:.3f}s")

# Test first batch
start = time.time()
x, y = next(it)
print(f"next(it): {time.time()-start:.3f}s")

64 raw __getitem__ calls: 1.305s
iter(dataloader): 0.002s
next(it): 6.538s


In [17]:
for points, target in tqdm(dataloader, total = len(dataloader)):
    pass

  0%|          | 2/456 [00:19<1:15:18,  9.95s/it]


KeyboardInterrupt: 

In [15]:
point.shape, target.shape

(torch.Size([16, 2048, 9]), torch.Size([16, 2048]))

In [16]:
point, target = point.float().cuda(), target.long().cuda()

In [17]:
out,_ = model(point.transpose(2,1))

In [17]:
out.shape

torch.Size([64, 8192, 47])

In [10]:
for i, (points, target) in tqdm(enumerate(dataloader), total=len(dataloader)):
    points, target = points.float().cuda(), target.float().cuda()
    points = points.transpose(2,1)

    out, _ = model(points)

  0%|          | 33/7285 [03:39<13:23:49,  6.65s/it]


KeyboardInterrupt: 